
x = """
id	int4	TRUE
external_id varchar FALSE
campaign_id	int4	FALSE
source_id	int4	FALSE
medium_id	int4	FALSE
access_token	varchar	FALSE
message_main_attachment_id	int4	FALSE
rating_last_value	float8	FALSE
name	varchar	FALSE
team_id	int4	FALSE
description	text	FALSE
active	bool	FALSE
ticket_type_id	int4	FALSE
company_id	int4	FALSE
color	int4	FALSE
kanban_state	varchar	TRUE
user_id	int4	FALSE
partner_id	int4	FALSE
partner_name	varchar	FALSE
partner_email	varchar	FALSE
priority	varchar	TRUE
stage_id	int4	FALSE
assign_date	timestamp	FALSE
assign_hours	int4	FALSE
close_date	timestamp	FALSE
close_hours	int4	FALSE
sla_id	int4	FALSE
sla_name	varchar	FALSE
deadline	timestamp	FALSE
sla_active	bool	FALSE
sla_fail	bool	FALSE
create_uid	int4	FALSE
create_date	timestamp	FALSE
write_uid	int4	FALSE
write_date	timestamp	FALSE
initiator_phone	varchar	FALSE
initiator	int4	FALSE
initiator_name	varchar	FALSE
order_type	int4	FALSE
service_type	int4	FALSE
order_status	int4	FALSE
ticket_type_group_id	int4	FALSE
order_number_moved0	varchar	FALSE
order_paid	bool	FALSE
ticket_responsibility_id	int4	FALSE
ticket_responsibility_description_id	int4	FALSE
order_url	varchar	FALSE
city_id	int4	FALSE
creator_name	varchar	FALSE
closer_name	varchar	FALSE
channel_id	int4	FALSE
parent_id	int4	FALSE
expiration_date	timestamp	FALSE
suggested_action	text	FALSE
driver_id_moved0	int4	FALSE
driver_name	varchar	FALSE
driver_phone	varchar	FALSE
customer_name	varchar	FALSE
customer_phone	varchar	FALSE
merchant_name	varchar	FALSE
pos_name	varchar	FALSE
pos_manager_name	varchar	FALSE
pos_manager_phone	varchar	FALSE
conversation_id	varchar	FALSE
message_id	varchar	FALSE
id_char	varchar	FALSE
reopened_ticket	bool	FALSE
conversation_ids	int4	FALSE
cc_lang	varchar	FALSE
cc_queue	varchar	FALSE
cc_vq_position	int4	FALSE
cc_wait_time_in_queue	int4	FALSE
cc_menu_num	int4	FALSE
first_user_id	int4	FALSE
assign_minutes	int4	FALSE
close_minutes	int4	FALSE
time_resolve_minutes	int4	FALSE
timer_start_moment	timestamp	FALSE
timer_resulting_value	varchar	FALSE
is_autocreated	bool	FALSE
chatbot_scenario	varchar	FALSE
is_sent_request_chatbot	bool	FALSE
initiator_id	varchar	FALSE
cc_call_id	varchar	FALSE
cc_call_type	varchar	FALSE
create_hour	timestamp	FALSE
was_disabling_rep	bool	FALSE
suspected_failure	float8	FALSE
recommend_responses	int4	FALSE
message_to_chat	text	FALSE
rfm_group_id	int4	FALSE
child_tickets	int4	FALSE
social_media_account	varchar	FALSE
social_media_platform	varchar	FALSE
agent_ticket_reason	int4	FALSE
action_taken	int4	FALSE
customer_language	varchar	FALSE
solved_date	timestamp	FALSE
search_time	int4	FALSE
time_to_pick_up	int4	FALSE
time_preparation	int4	FALSE
transaction_id	varchar	FALSE
is_fraud	bool	FALSE
is_sent_fraud_request_chatbot	bool	FALSE
selected_fraud_flow	varchar	FALSE
chat_bot_case_start	varchar	FALSE
initiator_email	varchar	FALSE
driver_id_moved1	varchar	FALSE
second_closer_name	varchar	FALSE
second_close_date	timestamp	FALSE
complains_rate	int4	FALSE
first_assign_date	timestamp	FALSE
firstCustomerResponseTime	timestamp	FALSE
avgCustomerResponseTime	int4	FALSE
first_agent_response_time	timestamp	FALSE
avg_agent_response_time	int4	FALSE
final_order_state	int4	FALSE
order_canceled_by	varchar	FALSE
cancelled_by_user_id	varchar	FALSE
cancelled_by_user_name	varchar	FALSE
chat_reason	varchar	FALSE
is_order_cancelled_by_agent	bool	FALSE
cancel_order_reason	int4	FALSE
chat_cancel_order_reason_id	int4	FALSE
chat_bot_cancel_key	varchar	FALSE
pos_id	varchar	FALSE
order_number	int4	FALSE
driver_id	int4	FALSE
quality_reason_id	int4	FALSE
quality_action_taker	int4	FALSE
compensation_rate	int4	FALSE
order	int4	FALSE
finished_time	timestamp	FALSE
issue_type_id	int4	FALSE
missing_products_price	float8	FALSE
missing_options_price	float8	FALSE
refund_transaction_status	varchar	FALSE
selected_tr_ids	varchar	FALSE
refund_policy_calculation_html	text	FALSE
customer_tier	int4	FALSE
customer_flag	varchar	FALSE
original_ticket_id	int4	FALSE
rated_user_id	int4	FALSE
original_ticket_rating	int4	FALSE
subscription_id	varchar	FALSE
subscription_name	varchar	FALSE
representative_id	int4	FALSE
subscription	int4	FALSE
autorefund_case_id	int4	FALSE
is_old_team_has_available_agent_rating	bool	FALSE
is_autorefund_case	bool	FALSE
product_type	varchar	FALSE
digital_order_id	int4	FALSE
digital_order_state	varchar	FALSE
account_manager_resolution_id	int4	FALSE
closer_user_id	int4	FALSE
is_created_by_wizard	bool	FALSE
is_copy	bool	FALSE
rank	int4	FALSE
rank_increment_date	timestamp	FALSE
sub_reason	int4	FALSE
"""
data = x.strip().split("\n")
import re
space = re.compile(r"\s+")

types_map = {
    "int4": "int32",
    "varchar": "string",
    "text": "string",
    "timestamp": "time.Time",
    "float8": "float32",
}

for i, line in enumerate(data, 1):
    line = space.split(line)
    field = line[0]
    field = field.split("_")
    field = "".join([f"{x.capitalize()}" for x in field])
    dtype = types_map.get(line[1], line[1])
    optional = "*" if line[2] == "FALSE" else ""
    print(f'{field} {optional}{dtype}')