import datetime
env = {}

k = env['aram.kafka']

k.process_bot_ticket_request([None, {'request_id': '5f79841f-95f0-449a-8d20-6c6a9c2f3e7b', 'request_type': 'create_ticket', 'data': {'user_id': '2375e43a-cd6e-4fc1-9d41-10c0e86baa8e', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966550051641', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '667c6357-0375-4b6d-8c09-8870f453b66c', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 5, 25, tzinfo=datetime.timezone.utc), 'order': 84882126, 'compensation_rate': 17, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}])

k.process_bot_ticket_request([None, {'request_id': '0e97f5fc-8ba0-4b8c-b1f4-cfc10a80c126', 'request_type': 'create_ticket', 'data': {'user_id': '94eabd4d-c1bc-47b7-a9dd-940947a51b49', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966570511475', 'stage': 'created', 'priority': 'urgent', 'reason': 'cust_wrong_items', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '2554989f-d471-41d4-b1f5-83ab606188b7', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 4, 35, tzinfo=datetime.timezone.utc), 'order': 84882019, 'compensation_rate': 0, 'rfm_group': '01. Champions', 'tier': 'New', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': False, 'missing_items': [{'item_line_id': '4e2bb469-2839-44c5-8475-4be0e036bcdd', 'item_product_id': 'bbdd992b-589d-4f36-add2-2a5f07c7cbcd', 'item_text': 'كومبو البرجر المدبل دجاج أب سايز', 'item_quantity': '1', 'item_price': '38', 'item_options': [{'option_id': '541049', 'option_name': 'بيبسي دايت وسط', 'option_quantity': '1', 'option_price': '0'}, {'option_id': '541063', 'option_name': 'البطاطس المقلية وسط', 'option_quantity': '1', 'option_price': '0'}]}], 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}])
env.cr.commit()

m={'request_id': 'eacefd3c-0ec8-46ba-89a3-a55dff280968', 'request_type': 'create_ticket', 'data': {'user_id': '312435', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966549358101', 'stage': 'closed', 'priority': None, 'reason': 'rep_top_up_balance', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '773cb374-819c-4e0d-879d-2036edc7feb9', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 5, 50, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}

k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '6c605ba7-993f-42ed-848f-09eec88c9097', 'request_type': 'create_ticket', 'data': {'user_id': '300990', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966578783656', 'stage': 'closed', 'priority': None, 'reason': 'rep_moves_wrong_direction_autoaccept', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '89945131-d9d0-403c-b687-fe3f64d6b13c', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 4, 10, tzinfo=datetime.timezone.utc), 'order': 84882161, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '9210bd29-5571-4926-a7b3-af0a83b881c0', 'request_type': 'create_ticket', 'data': {'user_id': '311307', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966596304585', 'stage': 'closed', 'priority': None, 'reason': 'rep_not_moving_autoaccept', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'b77fb4bc-3f26-41da-8204-e51572d0c176', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 5, 35, tzinfo=datetime.timezone.utc), 'order': 84882173, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '62a58311-ae16-4c1a-afb0-d3538faae2ba', 'request_type': 'create_ticket', 'data': {'user_id': '284206', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966559167221', 'stage': 'closed', 'priority': None, 'reason': 'rep_top_up_balance', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'f3f03f3e-ff1b-49ca-9dbf-f7ebafbc659b', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 6, 8, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '1412fa7f-0a1c-4dc6-ad9d-84ddb5a3a954', 'request_type': 'create_ticket', 'data': {'user_id': '310523', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966558340594', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'e037042b-c11b-41dd-8444-84a6af2093c9', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 7, 12, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '5a54a3e3-6b9e-4bf7-9ec3-a19c96669397', 'request_type': 'create_ticket', 'data': {'user_id': '310523', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966558340594', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'db6a5390-1f29-4ac3-8987-2e2d0fd7f36b', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 7, 32, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '27d4a1e8-9227-4296-996c-a11bb403efbe', 'request_type': 'create_ticket', 'data': {'user_id': '9cf08cb6-2cdf-4f48-ad50-0c64ad0b0fae', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966564690699', 'stage': 'created', 'priority': None, 'reason': 'cust_question_current_drop', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'bba64ece-f9d2-4e1a-a6ba-42aa305436d9', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 7, 41, tzinfo=datetime.timezone.utc), 'order': 84881463, 'compensation_rate': 1, 'rfm_group': '02. Loyal Customers', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '7fa85ba0-0711-4438-955a-0f3784ae4b15', 'request_type': 'create_ticket', 'data': {'user_id': '313550', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966533698600', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'e4526b0e-e809-443f-be83-d86be35b503c', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 8, 35, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'cfd26b3b-244d-4b22-a87e-c0def2c39bc0', 'request_type': 'create_ticket', 'data': {'user_id': 'd5ee11e1-0536-402d-a3bb-d12d9e474c8c', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966551175310', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '31d7aab1-3eaa-4e88-bff7-420689d45a85', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 8, 25, tzinfo=datetime.timezone.utc), 'order': 84882072, 'compensation_rate': 4, 'rfm_group': '02. Loyal Customers', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '84e7269d-93e5-4d24-807c-918f610a789d', 'request_type': 'create_ticket', 'data': {'user_id': 'cc87f35c-3168-483a-8440-290af0beaba4', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966534965067', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'f3452677-306c-41c5-b942-6a87b2735af8', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 9, 10, tzinfo=datetime.timezone.utc), 'order': 84882143, 'compensation_rate': 0, 'rfm_group': '02. Loyal Customers', 'tier': 'New', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '8118dca3-68aa-4aa6-95ff-3211d54c6a71', 'request_type': 'create_ticket', 'data': {'user_id': '176814', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966578204954', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '0f1f8200-f79c-4e37-b68a-5c5bf1ec02fa', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 9, 7, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'c044a4a3-b6f4-48cd-968e-0dc4e1a02e7f', 'request_type': 'reopen_ticket', 'data': {'user_id': 'bdbbfd71-bc00-4e90-8c5a-f6fced511b50', 'user_type': None, 'support_user': None, 'phone': None, 'stage': None, 'priority': None, 'reason': None, 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': None, 'case': None, 'cancellation_case': None, 'detail': None, 'case_start': None, 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': '__export__.helpdesk_ticket_48297828_6aa92062', 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '228c01d9-4591-4582-84ef-c7ed50556886', 'request_type': 'create_ticket', 'data': {'user_id': '290222', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966570645689', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'd0ba518e-e9ae-45bf-a768-5a0dff39d8d3', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 9, 20, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '0e59d9bf-e734-4cfd-be98-37927a6d8960', 'request_type': 'create_ticket', 'data': {'user_id': '299854', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966540809474', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_refused_to_pay', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'ff354e57-671c-4af5-bb68-6d6750cb6faf', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 9, 19, tzinfo=datetime.timezone.utc), 'order': 84881872, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': 'e11f48ef-5bdc-4471-bc59-6d45eb9ef9c8', 'request_type': 'create_ticket', 'data': {'user_id': '312479', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966556283099', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'a507c914-01bd-430a-b9da-53b985e1c578', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 9, 41, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '097e0a7d-4cbb-42ff-ac4f-6328facfbc45', 'request_type': 'create_ticket', 'data': {'user_id': '300717', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966545437912', 'stage': 'closed', 'priority': None, 'reason': 'rep_moves_wrong_direction_autoaccept', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '2b8dff4c-9ced-44fd-87ee-31477c5065a6', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 5, 51, tzinfo=datetime.timezone.utc), 'order': 84882118, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '5d2d8224-6192-4135-8219-bae49635cd59', 'request_type': 'create_ticket', 'data': {'user_id': '294975', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966536569750', 'stage': 'created', 'priority': None, 'reason': 'rep_cashier_refused_order', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '7c082857-f438-430d-8812-1dd4f7332caa', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 10, tzinfo=datetime.timezone.utc), 'order': 84881853, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '5683723d-98c3-417a-88e1-ee3a4bcb382b', 'request_type': 'create_ticket', 'data': {'user_id': '299759', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966599612026', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '80e5e33c-1978-4419-bc6d-3053b15e7a65', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 10, 48, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '68c21035-b86a-4a87-8e5d-c48d6efe6e3a', 'request_type': 'create_ticket', 'data': {'user_id': '816e39b6-6f7b-4579-8150-a39e59d6a409', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966549898871', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '3ab6c9c4-4a3a-415a-9daa-e1b2d17e9058', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 11, 19, tzinfo=datetime.timezone.utc), 'order': 84882199, 'compensation_rate': 6, 'rfm_group': '01. Champions', 'tier': 'Platinum', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'cfe87372-1529-49f3-b4e8-f7f51dadcd72', 'request_type': 'create_ticket', 'data': {'user_id': 'bee2348b-cc74-4701-8c2a-f25f4ebbba58', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966554145356', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'ec001ad8-c39c-4a16-b81c-ae4e1724c277', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 12, 19, tzinfo=datetime.timezone.utc), 'order': 84882205, 'compensation_rate': 2, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '257d6829-fccb-40f2-9dd1-aea6fc7c7690', 'request_type': 'create_ticket', 'data': {'user_id': '308740', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966590698650', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '2430a915-f610-49a6-aade-70f7812e5e56', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 12, 26, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '551779bf-d869-47f0-aba2-e2770a36e13f', 'request_type': 'create_ticket', 'data': {'user_id': '310741', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966545219860', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'bd905648-17d5-4383-9fbd-14cf4ae5a9b4', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 12, 39, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '45420368-dccb-4cad-8eff-eaba32381535', 'request_type': 'create_ticket', 'data': {'user_id': '270743', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966570586073', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '32ab194f-21c6-4fb5-8934-16ca28ad6043', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 13, 3, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '8b234859-06f7-4822-83eb-e274d1037735', 'request_type': 'create_ticket', 'data': {'user_id': '1ec04985-8c2b-4694-b1b8-897fb88e9a94', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966541127683', 'stage': 'closed', 'priority': None, 'reason': 'cust_app', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '79cacb20-c7e2-4a41-8ad7-1c9f855b27a1', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 12, 4, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': 2, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '771ef8ba-03aa-429f-9947-24a42cc1c9ba', 'request_type': 'create_ticket', 'data': {'user_id': '283324', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966576075618', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_cancel', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'ae99ca2b-e754-4245-855b-5fa174358f6f', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 13, 43, tzinfo=datetime.timezone.utc), 'order': 84881798, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '6668e714-399c-4843-875f-75cd2245502a', 'request_type': 'create_ticket', 'data': {'user_id': '301112', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966572963653', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '47970608-a50c-476e-9042-ba178c1ae913', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 14, 19, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'c154036e-ba42-499e-9b89-d076c441b5bf', 'request_type': 'create_ticket', 'data': {'user_id': 'c49817c7-83ec-44f8-b389-cff6c48e0023', 'user_type': 'Pos', 'support_user': 'support_merchant', 'phone': '+966544212116', 'stage': 'closed', 'priority': None, 'reason': 'pos_items', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '3e476e1a-6ecf-4372-8314-5b5d0d132b1a', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 14, 9, tzinfo=datetime.timezone.utc), 'order': 84882073, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': True, 'all_items': False, 'missing_items': [{'item_line_id': 'c2a7434c-8586-4b0c-9856-f34b96cfe343', 'item_product_id': '5c6fdc3b-ab85-44e7-9ce5-28b6790c3d99', 'item_text': 'Al Rabie Orange Juice', 'item_quantity': '2.0', 'item_price': '3.0', 'item_options': None}], 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '80bd3d17-6f8e-410b-9127-f4ef68805fdd', 'request_type': 'create_ticket', 'data': {'user_id': '274898', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966557322276', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_refused_to_pay', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '59d6b2e6-6f80-463b-93dd-8bae351c93fb', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 1, 41, 5, tzinfo=datetime.timezone.utc), 'order': 84881820, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '6beb1e22-57f4-4931-95db-fff08f31a642', 'request_type': 'create_ticket', 'data': {'user_id': 'e007fb6a-ac56-4665-983a-fa38e3f63b14', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966506299426', 'stage': 'created', 'priority': None, 'reason': 'cust_question_current_drop', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '8f8b9c6e-5b79-4d25-8ddd-f702fa943717', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 13, 23, tzinfo=datetime.timezone.utc), 'order': 84881820, 'compensation_rate': 0, 'rfm_group': None, 'tier': 'New', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'a62a37c4-8ce4-44d4-becb-41c13bbf52a1', 'request_type': 'create_ticket', 'data': {'user_id': '304888', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966574606910', 'stage': 'created', 'priority': None, 'reason': 'rep_tech_support', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '433a1d20-1b6c-442e-8c51-38688a598e3d', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 14, 54, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '7d0a77a9-1007-40f7-808f-a6d8bd698d1c', 'request_type': 'create_ticket', 'data': {'user_id': '266060', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966571672403', 'stage': 'closed', 'priority': None, 'reason': 'rep_top_up_balance', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '8e7db9c6-220e-446e-a1cd-48a2dcb39e27', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 22, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '4ab72605-4ace-4cca-884b-cd83e729724f', 'request_type': 'create_ticket', 'data': {'user_id': '298154', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966536940450', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '8f7486c1-c6ee-4a6b-bdaa-c17dc0cfe8c4', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 20, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '5e9b42d7-3c17-4f1f-840f-246fbbbbac46', 'request_type': 'create_ticket', 'data': {'user_id': '176814', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966578204954', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '7f8cb3bd-53fe-482e-aa92-582d213df8e7', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 30, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '4fc7b7bb-5057-4eb3-bcb3-abcb03124587', 'request_type': 'create_ticket', 'data': {'user_id': '298154', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966536940450', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'c20796b1-e551-453e-88c7-4af1cf2d4cec', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 41, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()



m={'request_id': '676469a8-89d5-43fd-b6c3-8a173a001328', 'request_type': 'create_ticket', 'data': {'user_id': '301428', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966511365052', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '5ade52f4-271c-4992-a391-4f7b9cac6f20', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 53, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '801bb5be-1684-41ef-95ac-7e8d060554aa', 'request_type': 'create_ticket', 'data': {'user_id': '298154', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966536940450', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '243bd329-cd1f-4933-85c9-72e23420aa19', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 16, 13, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '0208d4e3-a97d-4ca9-9549-1f4dcd4ba1aa', 'request_type': 'create_ticket', 'data': {'user_id': 'bdbbfd71-bc00-4e90-8c5a-f6fced511b50', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966506640743', 'stage': 'closed', 'priority': None, 'reason': 'cust_app', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '80be58f9-95a1-4149-8f91-f0c64a8c6e1e', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 58, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': 7, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '2394a314-98b2-4738-a16a-077d6956be3d', 'request_type': 'create_ticket', 'data': {'user_id': '9cedc7ab-85bb-4542-a5af-214186ca680c', 'user_type': 'Pos', 'support_user': 'support_merchant', 'phone': '+966508766550', 'stage': 'closed', 'priority': None, 'reason': 'cust_decision_items_cancel', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'b2da719b-e8bd-4feb-a406-f5621798f050', 'cancellation_case': 'pos_items_some_per_request', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 15, 38, tzinfo=datetime.timezone.utc), 'order': 84882244, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': True, 'all_items': False, 'missing_items': [{'item_line_id': '94d99ba0-19b2-43fd-9edb-682db0f1d145', 'item_product_id': 'ada847cd-0c2e-4ceb-ac17-e5551d9f695b', 'item_text': 'فرنش توست كيندر', 'item_quantity': '1.0', 'item_price': '25.0', 'item_options': None}], 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '2d11f26d-7a1a-46ea-801c-2078cffc7285', 'request_type': 'create_ticket', 'data': {'user_id': 'd3b24763-e50d-4198-9c69-5150dedca446', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966541691601', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'af986250-c769-454e-9fc9-32081c8c9fe5', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 17, 25, tzinfo=datetime.timezone.utc), 'order': 84882142, 'compensation_rate': 1, 'rfm_group': '01. Champions', 'tier': 'Gold', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '4666cf22-b23b-46eb-a577-b4a6aeea6c43', 'request_type': 'create_ticket', 'data': {'user_id': '311038', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966531870776', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'b7749ed6-d61f-47e1-b6a5-ceb4aea94055', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 17, 24, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '41fdc4aa-641d-40c4-81db-afea6f6f3fc3', 'request_type': 'create_ticket', 'data': {'user_id': '283324', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966576075618', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_cancel', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': 'b420349a-6792-4052-b5a5-e536077e5249', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 16, 54, tzinfo=datetime.timezone.utc), 'order': 84881798, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'c00571d9-0810-4c72-bbd4-717d63b6c89a', 'request_type': 'create_ticket', 'data': {'user_id': '146068', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966506920541', 'stage': 'created', 'priority': None, 'reason': 'rep_wants_transfer_from_wallet_full_amount', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '129e19c4-92f0-46cf-8204-6caf42cf0d04', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 17, 38, tzinfo=datetime.timezone.utc), 'order': 79781502, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': 'ro_central_province', 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '5aea5cfb-5e89-4d5b-82f2-d7983dfa057a', 'request_type': 'create_ticket', 'data': {'user_id': '268359', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966507422548', 'stage': 'created', 'priority': None, 'reason': 'rep_wants_transfer_from_wallet_full_amount', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '6f398556-f99c-450b-9934-fb555dce017b', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 17, 20, tzinfo=datetime.timezone.utc), 'order': 84881860, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': 'ro_western_province', 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m= {'request_id': '077c2a7a-bf0e-4e65-a63e-93aa4e318c70', 'request_type': 'create_ticket', 'data': {'user_id': '265215', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966558443976', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'c6a86da4-4f83-4af9-85f3-f7dd43be1e1f', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 18, 23, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '9b744690-5152-48b6-b7e8-9c399f8bd594', 'request_type': 'create_ticket', 'data': {'user_id': '252726', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966540656019', 'stage': 'closed', 'priority': None, 'reason': 'rep_top_up_balance', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '67a3fa72-1011-4f13-8efc-0e3a7f2e72dd', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 18, 21, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': 'b3584788-7f70-4a6d-809f-bd6704af28c3', 'request_type': 'create_ticket', 'data': {'user_id': '313579', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966570753611', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '06ad134c-07d9-4063-985e-725831904b2e', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 19, 2, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '1d84ae48-3f45-4b3b-9bdf-6171b429ff9b', 'request_type': 'create_ticket', 'data': {'user_id': '303354', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966506990147', 'stage': 'closed', 'priority': None, 'reason': 'rep_not_moving_autoaccept', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '86dc9c0d-e418-4374-a659-7c7c3d8227c6', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 12, 5, tzinfo=datetime.timezone.utc), 'order': 84882211, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'cac4b9d1-488e-4d69-a097-6f82e648d367', 'request_type': 'create_ticket', 'data': {'user_id': '310523', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966558340594', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location_autoaccept', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '4c4a3bb5-4296-4b05-a866-b19a84b86d38', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 19, 8, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '5c748f8c-1703-4169-9d13-f215b0c5f663', 'request_type': 'create_ticket', 'data': {'user_id': '310523', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966558340594', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '49c1cc44-f2c2-4313-b4c1-c218518597e7', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 19, 30, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'a034a1ac-9a08-4e2d-9866-a77c14e3d53e', 'request_type': 'create_ticket', 'data': {'user_id': '283324', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966576075618', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_cancel', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '5416eb8b-e2f5-4428-9b9f-897a0c31ddcc', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 19, 25, tzinfo=datetime.timezone.utc), 'order': 84881798, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '9dd39265-29ef-40a4-864a-6d99cdfae42a', 'request_type': 'create_ticket', 'data': {'user_id': '306856', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966542773195', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'd296e0fe-6a69-4763-a306-3542b9b36129', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 19, 3, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '982d642d-5d20-4608-a37e-b79a6ba5bdf3', 'request_type': 'create_ticket', 'data': {'user_id': 'cc87f35c-3168-483a-8440-290af0beaba4', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966534965067', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'c772f098-c183-4700-8962-a9e906983da2', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 20, 46, tzinfo=datetime.timezone.utc), 'order': 84882245, 'compensation_rate': 0, 'rfm_group': '02. Loyal Customers', 'tier': 'New', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '132e2b10-ab40-45c5-a946-b1f9205922a5', 'request_type': 'create_ticket', 'data': {'user_id': '301391', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966538807353', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '8db287b8-b69d-4a29-8b6a-15dfc4363e0b', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 21, 29, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '5ec0c787-72c2-414b-aa87-e08d4484bf24', 'request_type': 'create_ticket', 'data': {'user_id': '309320', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966502540225', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '2af10ce2-4e07-46ca-b7c4-c105af376e6a', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 21, 26, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '6ba8cc1d-d542-4a77-81c9-df2358773c20', 'request_type': 'create_ticket', 'data': {'user_id': '304865', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966511315735', 'stage': 'closed', 'priority': None, 'reason': 'rep_cust_answered', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '734dcecd-5053-4ccf-affa-b7b864efbf7c', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 1, 48, 39, tzinfo=datetime.timezone.utc), 'order': 84881681, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '5e4592f0-1546-4846-a2a2-b5a5a8f5cd37', 'request_type': 'create_ticket', 'data': {'user_id': '304865', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966511315735', 'stage': 'created', 'priority': None, 'reason': 'rep_not_order_related', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '29140ea2-9e92-465d-96f2-da00828d7fc3', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 23, 35, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'ba5a1541-589e-491a-a346-cf43f278268d', 'request_type': 'create_ticket', 'data': {'user_id': 'a420b91c-a4b9-4652-9875-aa5aa89d36a3', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966545255777', 'stage': 'closed', 'priority': None, 'reason': 'cust_cc_payment_failed', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '090d718b-6aa9-44ee-9630-ffe67629fa1e', 'cancellation_case': 'cust_payment_failed', 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 24, 31, tzinfo=datetime.timezone.utc), 'order': 84882281, 'compensation_rate': 0, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Green', 'autorefund_case': None, 'parent': True, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m={'request_id': '8dfd3112-24c2-46d4-9fbc-97084ec711a2', 'request_type': 'create_ticket', 'data': {'user_id': 'fc7b625e-e0b5-4e95-a998-580de88390fc', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966548018367', 'stage': 'closed', 'priority': None, 'reason': 'customer_missing_items_no_autorefund', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'e74be136-30ba-449b-bfad-185ba82715b5', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 18, 19, 57, 14, tzinfo=datetime.timezone.utc), 'order': 84882017, 'compensation_rate': 19, 'rfm_group': '01. Champions', 'tier': 'Blue', 'flag': 'Red', 'autorefund_case': None, 'parent': None, 'all_items': False, 'missing_items': [{'item_line_id': '7bde4861-8ba7-45cc-9770-18bbe1f8c09a', 'item_product_id': 'c93fe916-a250-4c14-be60-3412aba1059a', 'item_text': 'ماتشا فرابتشينو', 'item_quantity': '1', 'item_price': '21', 'item_options': [{'option_id': '1256526', 'option_name': 'كبير (٣٩٠ س.ح.)', 'option_quantity': '1', 'option_price': '4'}, {'option_id': '1256567', 'option_name': 'حليب جوز الهند', 'option_quantity': '1', 'option_price': '0'}]}, {'item_line_id': 'aa0c29f4-3311-4b21-87b2-87b5337e01d6', 'item_product_id': 'c93fe916-a250-4c14-be60-3412aba1059a', 'item_text': 'ماتشا فرابتشينو', 'item_quantity': '1', 'item_price': '21', 'item_options': [{'option_id': '1256526', 'option_name': 'كبير (٣٩٠ س.ح.)', 'option_quantity': '1', 'option_price': '4'}, {'option_id': '1256564', 'option_name': 'حليب كامل الدسم', 'option_quantity': '1', 'option_price': '0'}]}], 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m= {'request_id': '522fc46d-617b-4227-a205-eeedbc8bbf99', 'request_type': 'create_ticket', 'data': {'user_id': '283324', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966576075618', 'stage': 'created', 'priority': 'urgent', 'reason': 'rep_cust_cancel', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '8070bc19-0c5e-4e06-9fa0-5267c4995265', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 24, 57, tzinfo=datetime.timezone.utc), 'order': 84881798, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'ac4fc6cb-fcd2-4daa-b517-492007662e2f', 'request_type': 'create_ticket', 'data': {'user_id': '310425', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966534944511', 'stage': 'created', 'priority': None, 'reason': 'rep_wants_transfer_from_wallet_full_amount', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'ff495483-db04-45a4-8c11-752c214b6be8', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 24, 37, tzinfo=datetime.timezone.utc), 'order': 84878757, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': 'ro_central_province', 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'f080e16b-630e-4058-a748-b7e6f7290cd0', 'request_type': 'create_ticket', 'data': {'user_id': '304405', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966534052495', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '129b3c77-5cb2-4e92-9970-3bba6b27d512', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 1, 55, 21, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '26f57151-ba11-4ebb-ab9c-e66b9f4c1159', 'request_type': 'create_ticket', 'data': {'user_id': '312213', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966568509290', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'abfbfede-a6a4-44b3-af94-1fe05ec2c310', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 25, 39, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '2e643945-5e82-4e37-b4bf-c7cef30fa4f8', 'request_type': 'create_ticket', 'data': {'user_id': '153778', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966570100585', 'stage': 'created', 'priority': None, 'reason': 'rep_tech_support', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': 'a491b340-f79e-402b-b04d-0b47a1f6651a', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 25, 24, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': '76f910e6-d5b0-4365-b5b7-ca2b2f6bc668', 'request_type': 'create_ticket', 'data': {'user_id': '304865', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966511315735', 'stage': 'created', 'priority': None, 'reason': 'rep_not_order_related', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '907910f2-d81c-44d5-82cf-028dc7d49ac8', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 25, 9, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()

m={'request_id': 'edcdd234-3088-42be-8269-96a021a1dd14', 'request_type': 'create_ticket', 'data': {'user_id': 'c60fe8cc-d130-48af-a3b8-387af88e6da9', 'user_type': 'Customer', 'support_user': 'support_customer', 'phone': '+966590505336', 'stage': 'closed', 'priority': None, 'reason': 'cust_cancel_request', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'ar', 'case': '552e6972-a98f-4c3c-85f1-5eb011d80c1c', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 26, 13, tzinfo=datetime.timezone.utc), 'order': 84881850, 'compensation_rate': 2, 'rfm_group': '01. Champions', 'tier': 'Gold', 'flag': 'Green', 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()


m= {'request_id': 'a9206352-5467-4453-9422-7c0a940ac9b8', 'request_type': 'create_ticket', 'data': {'user_id': '302166', 'user_type': 'Rep', 'support_user': 'support_driver', 'phone': '+966535113858', 'stage': 'closed', 'priority': None, 'reason': 'rep_why_no_orders_step_no_close_hd_location', 'close_reason': None, 'reopen_reason': None, 'subscription_id': None, 'language': 'en', 'case': '601d371a-194d-4ba7-92b7-48b19fb03383', 'cancellation_case': None, 'detail': None, 'case_start': datetime.datetime(2024, 11, 20, 2, 27, 2, tzinfo=datetime.timezone.utc), 'order': None, 'compensation_rate': None, 'rfm_group': None, 'tier': None, 'flag': None, 'autorefund_case': None, 'parent': None, 'all_items': None, 'missing_items': None, 'tid': None, 'ticket_id': None, 'team': None, 'product_type': None, 'pos_id': None, 'order_id': None, 'ticket_external_id': None, 'is_fraud': None}}
k.process_bot_ticket_request([None, m])
env.cr.commit()
